//------------------------------------------------------------------------
// Copyright(c) 2022 Emanuele Messina.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"ReaShader.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"ReaShader VST3 (64Bit)"
#else
#define stringFileDescription	"ReaShader VST3"
#endif
#define stringCompanyName		"Emanuele Messina\0"
#define stringLegalCopyright	"Copyright(c) 2022 Emanuele Messina."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
